[build]
  publish = "staticfiles"
  command = "python manage.py collectstatic --noinput"

[build.environment]
  PYTHON_VERSION = "3.12"
  DJANGO_SETTINGS_MODULE = "mess_management.settings.production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/django/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/django/:splat"
  status = 200

[[redirects]]
  from = "/telegram/*"
  to = "/.netlify/functions/django/:splat"
  status = 200

[[redirects]]
  from = "/scanner/*"
  to = "/.netlify/functions/django/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
